services:
  db:
    image: postgres:17-alpine
    container_name: lobbym-postgres
    restart: always
    environment:
      POSTGRES_DB: lobbym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - lobbym_pg_data:/var/lib/postgresql/data
      - ../tmp:/tmp
    networks:
      - lobbym-network

  redis:
    image: redis:7-alpine
    container_name: lobbym-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lobbym-network

  lobbym-socket:
    build:
      context: ../../dev.api.lobbym.com/socket
      dockerfile: Dockerfile
    container_name: lobbym-socket
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@lobbym-postgres:5432/lobbym
      - JWT_SECRET=hCn5nyx49PHVeSbN1Aajzh5XUHNOj6xZ5CCupG3Pgl4xzNlv3sirodDRF6N2EnCY
      - PORT=3000
    networks:
      - lobbym-network

  lobbym-scraper:
    build:
      context: ../../dev.api.lobbym.com/scraper
      dockerfile: Dockerfile
    container_name: lobbym-scraper
    shm_size: '2gb'
    ports:
      - "8085:8085"
    networks:
      - lobbym-network
    environment:
      - SCRAPER_PROXY=gkxoynov-tr-rotate:zb2lsvs6o9uv@p.webshare.io:80
      - PYTHONUNBUFFERED=1

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: lobbym-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - lobbym_es_data:/usr/share/elasticsearch/data
    networks:
      - lobbym-network

  kibana:
    image: kibana:8.11.1
    container_name: lobbym-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://lobbym-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - lobbym-network

  cassandra:
    image: cassandra:5.0
    container_name: lobbym-cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - lobbym_cassandra_data:/var/lib/cassandra
    networks:
      - lobbym-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lobbym-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - lobbym_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lobbym-network

volumes:
  lobbym_pg_data:
  lobbym_es_data:
  lobbym_cassandra_data:
  lobbym_rabbitmq_data:

networks:
  lobbym-network:
    external: true
