services:
  # --- INFRASTRUCTURE ---
  db:
    image: postgres:17-alpine
    container_name: lobbym-postgres
    restart: always
    environment:
      POSTGRES_DB: lobbym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lobbym-network
  lobbym-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: lobbym-scraper
    ports:
      - "8085:8085"
    networks:
      - lobbym-network
    environment:
      - SCRAPER_PROXY=gkxoynov-tr-rotate:zb2lsvs6o9uv@p.webshare.io:80
      - PYTHONUNBUFFERED=1



  redis:
    image: redis:7-alpine
    container_name: lobbym-redis
    restart: always
    networks:
      - lobbym-network

  # --- MAIL SERVER (MAILU) ---
  front:
    image: ghcr.io/mailu/nginx:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
    volumes:
      - ./mailu/config:/config
      - ./mailu/data:/data
      - ./mailu/certs:/certs
    networks:
      - lobbym-network

  resolver:
    image: ghcr.io/mailu/unbound:2.0
    restart: always
    env_file: mailu.env
    networks:
      lobbym-network:
        ipv4_address: 172.22.0.254

  admin:
    image: ghcr.io/mailu/admin:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    volumes:
      - ./mailu/data:/data
      - ./mailu/dkim:/dkim
    networks:
      - lobbym-network

  imap:
    image: ghcr.io/mailu/dovecot:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    volumes:
      - ./mailu/data:/data
      - ./mailu/mail:/mail
      - ./mailu/overrides:/overrides
      - ./mailu/certs:/certs
    networks:
      - lobbym-network

  smtp:
    image: ghcr.io/mailu/postfix:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    volumes:
      - ./mailu/data:/data
      - ./mailu/overrides:/overrides
      - ./mailu/certs:/certs
    networks:
      - lobbym-network

  antispam:
    image: ghcr.io/mailu/rspamd:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    volumes:
      - ./mailu/filter:/var/lib/rspamd
    networks:
      - lobbym-network

  webmail:
    image: ghcr.io/mailu/webmail:2.0
    restart: always
    env_file: mailu.env
    dns:
      - 172.22.0.254
    volumes:
      - ./mailu/webmail:/data
    networks:
      - lobbym-network
  lobbym-socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    container_name: lobbym-socket
    restart: always
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:EiB6eish@db:5432/lobbym
      - JWT_SECRET=CYtHI1pjd47GsOU5eKkklRmNdnePdyx89J40VEmGqjCkJlYC1fEazWyd5HSbOmoW
      - PORT=3000
      - SSL_KEY_PATH=/certs/letsencrypt/live/mailu/privkey.pem
      - SSL_CERT_PATH=/certs/letsencrypt/live/mailu/fullchain.pem
    depends_on:
      - db
    volumes:
      - ./mailu/certs:/certs:ro
    networks:
      - lobbym-network

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: lobbym-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - lobbym-network

  kibana:
    image: kibana:8.11.1
    container_name: lobbym-kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://lobbym-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - lobbym-network

  cassandra:
    image: cassandra:5.0
    container_name: lobbym-cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - lobbym-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lobbym-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lobbym-network

volumes:
  pg_data:
  es_data:
  cassandra_data:
  rabbitmq_data:

networks:
  lobbym-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
